# Generated by Django 5.1.3 on 2024-12-18 13:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('username', models.CharField(default='default username', max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='User_info',
            new_name='UserInfo',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='fname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='lname',
            new_name='last_name',
        ),
    ]
